[package]
name = "octool"
version = "0.2.0"
authors = ["rusty-bits <rusty_bits@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = "^1"
hex = "^0"
serde_json = "^1"
sha2 = "^0"
fs_extra = "^1"
termion = "^1"
rand = "*"

[profile.release]
lto = true
