version: 2.1

orbs:
    windows: circleci/windows@2.4.1

jobs:
    build-linux:
        docker:
          - image: cimg/rust:1.57.0
        steps:
            - checkout
            - run:
                  name: "Generate Cargo.lock"
                  command: |
                      rustc --version >rust-version
                      test -e Cargo.lock || cargo generate-lockfile
            - restore_cache:
                  key: cargo-cache-{{ arch }}-{{ checksum "rust-version" }}-{{ checksum "Cargo.lock" }}
            - run:
                  name: "Build Release"
                  command: cargo build --release
            - save_cache:
                  paths:
                      - /usr/local/cargo/registry
                      - ./target
                  key: cargo-cache-{{ arch }}-{{ checksum "rust-version" }}-{{ checksum "Cargo.lock" }}

    build-windows:
        executor: windows/default
        environment:
            CARGO_NET_GIT_FETCH_WITH_CLI: "true"
        steps:
            - checkout
            - run:
                  name: "Install Rust"
                  command: |
                      $ProgressPreference = "SilentlyContinue"
                      Invoke-WebRequest -Uri "https://win.rustup.rs/" -OutFile "C:\rustup-init.exe"
                      & C:\rustup-init.exe -y --default-toolchain "stable-x86_64-pc-windows-msvc" --no-modify-path --profile minimal
                      $env:Path += ";C:\Users\circleci\.cargo\bin"
                      rustc -Vv
                      cargo --version
                      rustc --version | Out-File -FilePath "rust-version"
                      if (!(Test-Path "Cargo.lock" -PathType Leaf)) {
                          cargo generate-lockfile
                      }
            - restore_cache:
                  key: cargo-cache-{{ arch }}-{{ checksum "rust-version" }}-{{ checksum "Cargo.lock" }}
            - run:
                  name: "Build Release"
                  command: cargo build --release
            - save_cache:
                  paths:
                      - C:\Users\circleci\.cargo\registry
                      - target
                  key: cargo-cache-{{ arch }}-{{ checksum "rust-version" }}-{{ checksum "Cargo.lock" }}
            - store_artifacts:
                  path: build\\release
                  destination: releases
            - persist_to_workspace:
                  root: build
                  paths:
                      - release

workflows:
    version: 2
    build-releases:
        jobs:
            - build-linux:
            - build-windows:
